heat_template_version: 2015-10-15

description: >
  Creates a port on the baremetal network. The IP address will be chosen
  automatically if FixedIPs is empty.

parameters:
  BaremetalNetName:
    description: Name of the baremetal neutron network
    default: baremetal
    type: string
  PortName:
    description: Name of the port
    default: ''
    type: string
  ControlPlaneIP: # Here for compatibility with noop.yaml
    description: IP address on the control plane
    type: string
  IPPool: # Here for compatibility with from_pool.yaml
    default: {}
    type: json
  NodeIndex: # Here for compatibility with from_pool.yaml
    default: 0
    type: number

resources:

  BaremetalPort:
    type: OS::Neutron::Port
    properties:
      network: {get_param: BaremetalNetName}
      name: {get_param: PortName}
      replacement_policy: AUTO

outputs:
  ip_address:
    description: baremetal network IP
    value: {get_attr: [BaremetalPort, fixed_ips, 0, ip_address]}
  ip_address_uri:
    description: baremetal network IP (for compatibility with baremetal_v6.yaml)
    value: {get_attr: [BaremetalPort, fixed_ips, 0, ip_address]}
  ip_subnet:
    description: IP/Subnet CIDR for the baremetal network IP
    value:
          list_join:
            - ''
            - - {get_attr: [BaremetalPort, fixed_ips, 0, ip_address]}
              - '/'
              - {str_split: ['/', {get_attr: [BaremetalPort, subnets, 0, cidr]}, 1]}
